version: '3.8'
services:
  app:
    image: madsakselsen/weather-service:latest  # Use the image from your Docker registry
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - app.env  # This file will be created on the fly in your GitHub Actions workflow
    environment:
      - REDIS_ADDR=redis:6379
      - OPEN_WEATHER_MAP_URL=https://api.openweathermap.org/data/2.5
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
volumes:
  redis-data:
