version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - config/local.env
    environment:
      REDIS_ADDR: redis:6379
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
